### ISSUE TITLE
NullPointerException in TaskResource when ownerId is not set (NULL)

### ISSUE THREAD

**Issue by astanik** [remsfal/remsfal-backend#227]
How to Reproduce?
- Create a new task (POST) without ownerId
- Retrieve all tasks (GET)

Stacktrace:
Exception in TaskResource.java:31
	   29          checkPrivileges(projectId);
	   30          if(ownerId == null || ownerId.isBlank()) {
	-> 31              return TaskListJson.valueOf(taskController.getTasks(projectId, Optional.ofNullable(status)));
	   32          } else {
	   33              return TaskListJson.valueOf(taskController.getTasks(projectId, ownerId, Optional.ofNullable(status)));

: org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException: owner
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:107)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invokePropagateNotFound$6(SynchronousDispatcher.java:275)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:260)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:86)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.NullPointerException: owner
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at de.remsfal.core.json.project.ImmutableTaskItemJson$Builder.owner(ImmutableTaskItemJson.java:399)
	at de.remsfal.core.json.project.TaskItemJson.valueOf(TaskItemJson.java:42)
	at de.remsfal.core.json.project.TaskListJson.valueOf(TaskListJson.java:28)
	at de.remsfal.service.boundary.project.TaskResource.getTasks(TaskResource.java:31)
	at de.remsfal.service.boundary.project.TaskResource_Subclass.getTasks$$superforward(Unknown Source)
	at de.remsfal.service.boundary.project.TaskResource_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:38)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at de.remsfal.service.boundary.project.TaskResource_Subclass.getTasks(Unknown Source)
	at de.remsfal.service.boundary.project.TaskResource_ClientProxy.getTasks(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	... 16 more

**Comment by Quirtelus** [comment]
Ich würde gerne das als good first issue nehmen

**Comment by Quirtelus** [comment]
Beim fixxen des Issues ist mir aufgefallen, dass wenn ich den create Task mit null oder leeren Strings als Userdaten ausführe ich ebenfalls einen Fehler kriege.  Habe ich nen denkfehler im Test oder ist da eine Codetechnischer Fehler?
```
//Test für Task anlegen ohne ownerID
    @ParameterizedTest(name = "{displayName} - {arguments}")
    @ValueSource(strings = { TASK_PATH, DEFECT_PATH })
    void createTask_SUCCESS_taskIsCreated_USERID_isNull(String path) {
        final String json = "{ \"title\":\"" + TestData.TASK_TITLE + "\"}";
        given()
                .when()
                .cookie(buildCookie(null, null, Duration.ofMinutes(10)))
                .contentType(ContentType.JSON)
                .body(json)
                .post(path, TestData.PROJECT_ID)
                .then()
                .statusCode(Status.CREATED.getStatusCode())
                .contentType(ContentType.JSON)
                .header("location", Matchers.containsString(path.replace("{projectId}", TestData.PROJECT_ID)))
                .and().body("id", Matchers.notNullValue())
                .and().body("title", Matchers.equalTo(TestData.TASK_TITLE));

        long enties = entityManager
                .createQuery("SELECT count(task) FROM TaskEntity task where task.title = :title", Long.class)
                .setParameter("title", TestData.TASK_TITLE)
                .getSingleResult();
        assertEquals(1, enties);
    }
```

**Comment by astanik** [comment]
@Quirtelus Can you please create a pull request with your changes, because i can not see where and how you made your changes.
